#!/opt/perl/bin/perl

my %versions;
my %from;

while (<STDIN>) {
   chomp;
   my ($from, $name, $version, $os) = split /\t/, $_;
   next if $from{$from};
   $from{$from} = 1;
   $versions{$name .": " . $version}++;
}

for (sort { $versions{$a} <=> $versions{$b} } keys %versions) {
   printf "%3d: %s\n", $versions{$_}, $_;
}
