#!/opt/perl/bin/perl
use strict;
use utf8;
use AnyEvent;
use Net::XMPP2::Client;

my $j = AnyEvent->condvar;
my $cl = Net::XMPP2::Client->new (debug => 1);
$cl->add_account ('net_xmpp2@jabber.org', 'test');
$cl->reg_cb (
   session_ready => sub {
      my ($cl, $acc) = @_;
      print "session ready\n";
      my $msg =
         Net::XMPP2::IM::Message->new (
            to   => 'elmex@jabber.org/tkabber',
            body => 'test'
         );
      $msg->append_creation (sub {
        my ($w) = @_;
        $w->raw ('<a:b/>');
      });

      $acc->connection->reg_cb (send_buffer_empty => sub {
         warn "DONE SENDING";
         $acc->connection->disconnect ("sent message");
      });
      $msg->send ($acc->connection);
      $acc->connection->drain;
   },
   disconnect => sub {
      my ($cl, $acc, $h, $p, $reas) = @_;
      print "disconnect ($h:$p): $reas\n";
      $j->broadcast;
   },
   error => sub {
      my ($cl, $acc, $err) = @_;
      print "ERROR: " . $err->string . "\n";
   },
   message => sub {
      my ($cl, $acc, $msg) = @_;
      print "message from: " . $msg->from . ": " . $msg->any_body . "\n";
   }
);
$cl->start;
$j->wait;
