#!/opt/perl/bin/perl
use strict;
use utf8;
use AnyEvent;
use Net::XMPP2::IM::Connection;

unless (@ARGV >= 3) { die "sendmsg <account jid> <password> <destination jid>\n" }

my $msg  = do { local $/; <STDIN> };
my $dest = $ARGV[2];

my $j = AnyEvent->condvar;

my $con =
   Net::XMPP2::IM::Connection->new (
      jid      => $ARGV[0],
      password => $ARGV[1],
    #  initial_presence => -10,
      debug    => 1
   );

$con->reg_cb (
   session_ready => sub {
      my ($con) = @_;
      print "Connected as " . $con->jid . "\n";
      print "Sending message to $dest:\n$msg\n";
      my $immsg = Net::XMPP2::IM::Message->new (to => $dest, body => $msg);
      $immsg->send ($con);
   },
   error => sub {
      my ($con, $error) = @_;
      warn "Error: " . $error->string . "\n";
   },
   disconnect => sub {
      my ($con, $h, $p, $reason) = @_;
      warn "Disconnected from $h:$p: $reason\n";
      $j->broadcast;
   },
   debug_send => sub { warn "send: @_\n" },
   debug_recv => sub { warn "recv: @_\n" },
);

print "Trying to connect...\n";
$con->connect ();

$j->wait;
