#!/opt/perl/bin/perl
use strict;
use utf8;
use Event;
use AnyEvent;
use Net::XMPP2::Client;
use Net::XMPP2::Ext::Disco;
use Net::XMPP2::Ext::MUC;

my $j = AnyEvent->condvar;
my $cl = Net::XMPP2::Client->new (debug => 1);
$cl->add_account ('net_xmpp2@jabber.org', 'test');
$cl->add_extension (my $disco = Net::XMPP2::Ext::Disco->new);
my $muc;
$cl->reg_cb (
   session_ready => sub {
      my ($cl, $acc) = @_;
      $muc =
         Net::XMPP2::Ext::MUC->new (connection => $acc->connection, disco => $disco);
      $cl->add_extension ($muc);
      $muc->join_room ('test@conference.ejabberd.ta-sa.org', "TestBot", sub {
         my ($err) = @_;
         if ($err) {
            print "ERROR" . $err->string . "\n";
         } else {
            print "JOINED!\n";
         }
      });
   },
   disconnect => sub {
      my ($cl, $acc, $h, $p, $reas) = @_;
      print "disconnect ($h:$p): $reas\n";
   },
   error => sub {
      my ($cl, $acc, $err) = @_;
      print "ERROR: " . $err->string . "\n";
   },
   message => sub {
      my ($cl, $acc, $msg) = @_;
      print "message from: " . $msg->from . ": " . $msg->any_body . "\n";
   }
);
$cl->start;
$j->wait;
