#!/opt/perl/bin/perl
use strict;
use utf8;
use Event;
use AnyEvent;
use XML::Twig;
use Net::XMPP2 qw/xep-86/;
use Net::XMPP2::Client;
use Encode;

sub dumpxml {
   my $data = shift;
   my $t = XML::Twig->new;
   if ($t->safe_parse ("<deb>$data</deb>")) {
      $t->set_pretty_print ('indented');
      $t->print;
      print "\n";
   } else {
      print "[$data]\n";
   }
}

binmode STDOUT, ":utf8";

my $j = AnyEvent->condvar;

my $cl = Net::XMPP2::Client->new;
$cl->add_account ('elmor@jabber.org/Net::XどなPP2', 'xxxxxxxx');
$cl->reg_cb (
   connected => sub {
      $cl->send_message ("Hello!" => 'elmex@jabber.org');
      0
   },
);

$cl->start;

$j->wait;
